let pc_data = [{
    img: "https://drive.google.com/uc?export=download&id=1OLn-frTjxMKF2P3S5Zt8omfXEq06tOEj",
    title: "HP Pavilion 27-ca2000ni 13th Gen Core i7 All-in-One PC",
    price: "4999",
    rent: "Rent ₹4999/month",
    color: "Color: Pearl White Fabric",
    desc: "Included Components: User Manual, Wireless Keyboard, Power Cable, Wireless Mouse, All In One (AIO)",
    operating_system: "Operating System: Windows 11 Home (64bit)",
    cpu: "CPU Type: Intel 13th Gen Core i7-13700T Processor",
    screen: "Screen: 27 FHD IPS-Level Touchscreen Display",
    memory: "Memory Size: 16GB DDR4 Memory",
    hard_disk: "Hard Disk: 512GB Ultra-Fast NVME SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: NVDIA® Geforce GTX 1650 with 4GB GDDR6",
    dimension: "Dimensions: 61.41 x 20.81 x 47.13 cm",
    weight: "Net Weight: 8.3 kg",
    brand: "Brand: HP",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1Fz-hQrdXwSNIfg7qF8gW7JDvD_Wmv-yg",
    title: "Dell AIO Inspiron 5410, Intel i5-1235U, Windows 11 + MSO'21, 8GB DDR4, 512GB SSD, Windows 11 + MSO'21, 23.8 inch FHD AG Narrow Border, Wireless Keyboard + Mouse, Black Color (BLK-3YR-D262196WIN9)",
    price: "2999",
    rent: "Rent ₹2999/month",
    color: "Color: Black",
    desc: "Included Components: User Manual, Wireless Keyboard, Power Cable, Wireless Mouse, All In One (AIO)",
    operating_system: "Operating System: Windows 11 Home (64bit)",
    cpu: "CPU Type: Intel 12th Gen Core i5-1235U Processor",
    screen: "Screen: 23.8 FHD IPS Display, with a 4-sided narrow border and 99% sRGB color gamut",
    memory: "Memory Size: 8GB DDR4 Memory",
    hard_disk: "Hard Disk: 512GB SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: NVIDIA® GeForce RTX™ 4080 12GB GDDR6",
    features: "Features: FHD Pop-up Camera",
    dimension: "Dimensions: 4 x 35.8 x 35.3 cm",
    weight: "Net Weight: 5.39 kg",
    brand: "Brand: DELL",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1M0shmX5EWsh0WflO_D5yixx2je1Dz1cq",
    title: "Lenovo IdeaCentre AIO 3 12th Gen Intel i5 23.8 inch FHD WVA 3-Side Edgeless All-in-One Desktop with Alexa Built-in (8GB/512GB SSD/Win11/MS Office 2021/IR Camera/Wireless Keyboard & Mouse) F0GH00MHIN",
    price: "2799",
    rent: "Rent ₹2799/month",
    color: "Color: Black",
    desc: "Included Components: User Manual, Wireless Keyboard, Power Cable, Wireless Mouse, All In One (AIO)",
    operating_system: "Operating System: Windows 11 Home (64bit)",
    cpu: "CPU Type: Intel 12th Gen Core i5 Processor",
    screen: "Screen: 23.8 inch FHD WVA 3-Side Edgeless Display",
    memory: "Memory Size: 8GB DDR4 Memory",
    hard_disk: "Hard Disk: 512GB SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: Intel Integrated Graphics",
    features: "",
    dimension: "Dimensions: 18.5 x 54.1 x 43.4 cm",
    weight: "Net Weight: 7.03 kg",
    brand: "Brand: LENOVO",
    desc: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1R9I7lY2LiMinxMnV1fRbTeh0MFsH-nuE",
    title: "ASUS AiO A3 Series, 23.8 inch (60.45 cm) FHD, Intel Core i5-1235U 12th Gen, All-in-One Desktop (8GB/512GB SSD/Windows 11/Office 2021/with Wireless Keyboard & Mouse/Black/5.4 kg), A3402WBAK-BA011WS",
    price: "2599",
    rent: "Rent ₹2599/month",
    color: "Color: Black",
    desc: "Included Components: AIO Desktop, Power Adaptor, User Manuals, Warranty Documents, Wireless Grey keyboard, Wireless optical mouse",
    operating_system: "Operating System: Windows 11 Home (64bit)",
    cpu: "CPU Type: Intel 12th Gen Core i5-1235U Processor",
    screen: "Screen: 88% screen-to-body ratio. With a 23.8 inch FHD (1920 x 1080) display",
    memory: "Memory Size: 16GB DDR4 Memory",
    hard_disk: "Hard Disk: 512GB PCIe 3.0 SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: Intel® UHD Graphics",
    features: "Features: 2x 3W Built-in speakers, Bluetooth, Wi-Fi 6",
    dimension: "Dimensions: 42.3 x 53.9 x 1.5 cm",
    weight: "Net Weight: 5.4 kg",
    brand: "Brand: ASUS",
    desc: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1DL3sumZD-WE1nlTlQTg3bJw_nNbgEj7a",
    title: "Apple 2023 Mac Mini Desktop Computer M2 Pro chip with 10‑core CPU and 16‑core GPU, 16GB Unified Memory, 512GB SSD Storage, Gigabit Ethernet. Works with iPhone/iPad",
    price: "7999",
    rent: "Rent ₹7999/month",
    color: "Color: Silver",
    desc: "Included Components: Power cord, Mac mini",
    operating_system: "Operating System: Mac OS",
    cpu: "CPU Type: M2 PRO",
    screen: "",
    memory: "Memory Size: 16GB",
    hard_disk: "Hard Disk: 512GB SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "",
    features: "",
    dimension: "",
    weight: "",
    brand: "Brand: APPLE",
    desc: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1FKICeyI0hxKPJUM2IR9ibSM37QV4vPM3",
    title: "Apple 2022 Mac Studio M1 Ultra chip with 20‑core CPU and 48‑core GPU, 64GB RAM, 1TB SSD - Silver",
    price: "29999",
    rent: "Rent ₹29999/month",
    color: "Color: Silver",
    desc: "Included Components: Power cord, Mac Studio",
    operating_system: "Operating System: Mac OS",
    cpu: "CPU Type: M1 Ultra",
    screen: "",
    memory: "Memory Size: 48GB",
    hard_disk: "Hard Disk: 1TB SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "",
    features: "",
    dimension: "",
    weight: "",
    brand: "Brand: APPLE",
    desc: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1ySZpitdfuBzy2JIlJjS8N8FMeeLcKvae",
    title: "Apple iMac 24-inch with Retina 4.5K display, 256GB - ImagineOnline Blue",
    price: "8999",
    rent: "Rent ₹8999/month",
    color: "Color: Blue ",
    desc: "Included Components: Power cord, Apple iMac",
    operating_system: "Operating System: Mac OS",
    cpu: "CPU Type: M1 Chip",
    screen: "Screen: 24 inch 4.5K Retina Display",
    memory: "Memory Size: 8GB",
    hard_disk: "Hard Disk: 256GB SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "",
    features: "",
    dimension: "",
    weight: "",
    brand: "Brand: APPLE",
    desc: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1RzT-S99H5pQVTxU_A6tMllMFYjSVCaNn",
    title: "Lenovo Legion Tower 5 Gaming Desktop (AMD Ryzen 7 5800/16GB/512GB SSD/2TB HDD/Win11/NVIDIA RTX 3070 8GB GDDR6/Legion ColdFront 2.0 Cooling/ARGB Lighting with 16 Million Colors/Transparent Side Panel)",
    price: "4999",
    rent: "Rent ₹4999/month",
    color: "Color: Black",
    desc: "Included Components: USB Calliope Keyboard, User Guide, USB Calliope Mouse, Desktop",
    operating_system: "Operating System: Windows 11 Home (64bit)",
    cpu: "CPU Type: AMD Ryzen 7 5800",
    screen: "",
    memory: "Memory Size: 8GB DDR4 Memory",
    hard_disk: "Hard Disk: 512GB SSD & 2TB HDD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: NVIDIA® RTX 3070 8GB GDDR6",
    features: "",
    dimension: "Dimensions: 20.5 x 39.6 x 41.1 cm",
    weight: "Net Weight: 14 kg",
    brand: "Brand: Lenovo",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1t182e9k7IjtmFoeDHiRH2fYx-R3RMwtR",
    title: "Kuro RTX Gaming PC RGB - Intel 12th Gen i7 (Alder Lake - 12C/20T), 32GB DDR4 RAM, 500GB SSD, GeForce RTX 3060Ti 8GB Graphics, WiFi Ready, Win 11 Pro",
    price: "6999",
    rent: "Rent ₹6999/month",
    color: "Color: Black",
    desc: "Included Components: Kuro PC",
    operating_system: "Operating System: Windows 11 PRO",
    cpu: "CPU Type: Intel 12th Gen i7 (Alder Lake - 12C/20T)",
    screen: "",
    memory: "Memory Size: 32GB DDR4 Memory",
    hard_disk: "Hard Disk: 500GB SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: GeForce RTX 3060Ti 8GB Graphics",
    features: "",
    dimension: "Dimensions: 20.5 x 39.6 x 41.1 cm",
    weight: "Net Weight: 16 kg",
    brand: "Brand: Kuro Gaming (System Integrator)",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1pdV5iHikmlBhCJSqCJiyeP6Dwvve0pMv",
    title: "Dell Alienware Aurora (R13) Gaming Desktop, Intel i7-12700KF, 16GB, 1TB + 512GB SSD, NVIDIA RTX 3070 (8GB GDDR6 LHR),Windows 11, Silver, 16.5Kgs (D269920WIN9)",
    price: "6999",
    rent: "Rent ₹6999/month",
    color: "Color: Silver(Lunar Light)",
    desc: "Included Components: No Monitor, System Power Cord (India)",
    operating_system: "Operating System: Windows 11",
    cpu: "CPU Type:  Intel i7-12700KF 12th Gen",
    screen: "",
    memory: "Memory Size: 16GB DDR5 Memory",
    hard_disk: "Hard Disk: 1TB HDD + 512GB SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: Nvidia® Ge Force Rtx 3070 8 GB GDDR6",
    features: "",
    dimension: "Dimensions: 58 x 22.5 x 51 cm",
    weight: "Net Weight: 16.5 kg",
    brand: "Brand: DELL",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
]

let laptop_data = [{
    img: "https://drive.google.com/uc?export=download&id=1Cvl0mS43v6LkL8ta5QjvOXlziRzZdnnH",
    title: "MSI Bravo 17 Gaming Laptop, AMD Ryzen 7 7735HS, 43CM FHD 144Hz Laptop (16GB/1TB NVMe SSD/Windows 11 Home/Nvidia GeForce RTX 4050, GDDR6 6GB/Black/2.7Kg), C7VEK-035IN",
    price: "4999",
    rent: "Rent ₹4999/month",
    color: "Color: Black",
    desc: "Included Components: Laptop, Power Adapter",
    operating_system: "Operating System: Windows 11 Home (64bit)",
    features: "Batteries: 53.5 Watt Hours",
    cpu: "CPU Type: AMD Ryzen 7 7735HS",
    screen: "Screen: 1920 x 1080 pixels, 43 Centimetres, FHD 144Hz ",
    memory: "Memory Size: 16GB DDR5 Memory",
    hard_disk: "Hard Disk: 1TB NVMe SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: NVIDIA® GeForce RTX 4050 6GB GDDR6",
    dimension: "Dimensions: 52.9 x 33.6 x 8.8 cm",
    weight: "Net Weight: 2.7 kg",
    brand: "Brand: MSI",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1lD7SUf7tdLWBzEbB46E7iO4OfHtAQpPL",
    title: "Dell G15-5520 Gaming Laptop, Intel Core i9-12900H, 16GB DDR5, 1TB SSD, NVIDIA RTX 3060 (6GB GDDR6), 15.6 inch (39.62cm) FHD 165Hz 300 nits, Windows 11 + MSO'21, 15 Month McAfee, Dark Shadow Grey, 2.81kg",
    price: "5999",
    rent: "Rent ₹5999/month",
    color: "Color: Dark Shadow Grey",
    desc: "Included Components: User Manual, Laptop, Charger & Adapter",
    operating_system: "Operating System: Windows 11 Home (64bit)",
    features: "",
    cpu: "CPU Type: 12th Generation Intel Core i9-12900H (24MB Cache, up to 3.80 GHz, 14 cores) Processor",
    screen: "Screen: 1920 x 1080 pixels, 15.6-inch , FHD 165Hz ",
    memory: "Memory Size: 16GB DDR5 Memory",
    hard_disk: "Hard Disk: 1TB NVMe SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: NVIDIA® GeForce RTX 3060 6GB GDDR6",
    dimension: "Dimensions: 27.2 x 35.7 x 2.7 cm",
    weight: "Net Weight: 2.81 kg",
    brand: "Brand: DELL",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1SbLaCREwdWKvoPe5FyCzraKI-QD1pHXt",
    title: "HP Victus Gaming Laptop 15, 12th Gen Intel Core i7-12650H, 15.6-inch (39.6 cm), NVIDIA GeForce RTX 3050, FHD, 16GB DDR4, 512GB SSD, Backlit KB, Audio by B&O (Win 11, MSO 2021, Blue, 2.29 kg),fa0188TX",
    price: "4499",
    rent: "Rent ₹4499/month",
    color: "Color: Blue",
    desc: "Included Components: User Manual, Laptop, Charger & Adapter",
    operating_system: "Operating System: Windows 11 Home (64bit)",
    features: "Special Features: FHD, Backlit Keyboard, Micro-Edge Display, Anti-Glare",
    cpu: "CPU Type: 12th Gen Intel Core i7-12650H",
    screen: "Screen: 1920 x 1080 pixels, 15.6-inch , FHD 144Hz ",
    memory: "Memory Size: 16GB DDR4 Memory",
    hard_disk: "Hard Disk: 512GB SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: NVIDIA® GeForce RTX 3050 4GB GDDR6",
    dimension: "Dimensions: 51.9 x 31 x 7.3 cm",
    weight: "Net Weight: 2.37 kg",
    brand: "Brand: HP",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=12RnTsZXECEguOfrV23Z4FXL-gIAHvrBe",
    title: "ASUS ROG Strix G18 (2023) 90WHr Battery, Intel Core i7-13650HX 13th Gen, 18-inch FHD+ 165Hz, 8GB RTX 4060, Gaming Laptop (16GB/1TB SSD/Windows 11/Office 2021/Per-Key RGB/Green/3.00 Kg), G814JV-N5064WS",
    price: "6999",
    rent: "Rent ₹6999/month",
    color: "Color: Blue",
    desc: "Included Components: User Manual, Laptop, Charger & Adapter",
    operating_system: "Operating System: Windows 11 Home (64bit)",
    features: "Special Features: FHD, RGB Backlit Keyboard, Micro-Edge Display, Anti-Glare",
    cpu: "CPU Type: Core i7-13650HX 13th Gen",
    screen: "Screen: 1920 x 1200 pixel, 18-inch , FHD+ 165Hz ",
    memory: "Memory Size: 16GB DDR4 Memory",
    hard_disk: "Hard Disk: 1TB PCle 4.0 SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: NVIDIA® GeForce RTX 4060 8GB GDDR6",
    dimension: "Dimensions: 46 x 35.1 x 10.9 cm",
    weight: "Net Weight: 3 kg",
    brand: "Brand: ASUS",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1oTjWX0yMvUNFDP3HmUkZZTy3192fUylg",
    title: "Apple 2023 MacBook Pro Laptop M2 Pro chip with 12‑core CPU and 19‑core GPU: 33.74 cm (16.2-inch), 16GB Unified Memory, 1TB SSD Storage. Works with iPhone/iPad; Space Grey",
    price: "9999",
    rent: "Rent ₹9999/month",
    color: "Color: Space Grey",
    desc: "Included Components: 16-inch MacBook Pro, USB-C to MagSafe 3 Cable (2 m), 140W USB-C Power Adapter",
    operating_system: "Operating System: Mac OS",
    features: "Special Features: ADVANCED CAMERA AND AUDIO — Look sharp and sound great with a 1080p FaceTime HD camera, a studio-quality three-mic array, and a six-speaker sound system with Spatial Audio.",
    cpu: "CPU Type: M2 Pro chip with 12‑core CPU and 19‑core GPU",
    screen: "Screen: 16.2-inch (diagonal) mini-LED backlit Liquid Retina XDR display",
    memory: "Memory Size: 16GB",
    hard_disk: "Hard Disk: 512GB SSD",
    optical_drive: "Optical Drive: No DVD Drive Included",
    graphics: "Graphics Card: Integrated",
    dimension: "Dimensions: 14.01 inches (35.57 cm) X 9.77 inches (24.81 cm) [w X d]",
    weight: "Net Weight: 3 kg",
    brand: "Brand: APPLE",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
]
let tablet_data = [{
    img: "https://drive.google.com/uc?export=download&id=1qF6aSMTbU12wPihlcsrOetOFAwsepfpN",
    title: "Xiaomi Pad 6| Qualcomm Snapdragon 870| 144Hz Refresh Rate| 8GB, 256GB| 2.8K+ Display (11-inch/27.81cm)|1 Billion Colours| Dolby Vision Atmos| Quad Speakers| Wi-Fi| Gray",
    price: "999",
    rent: "Rent ₹999/month",
    color: "Color: GRAY",
    desc: "Included Components: Tablet, Adapter, USB C type Cable, Quick start Guide & Warranty card",
    operating_system: "Operating System: Android",
    features: "Batteries: 8840mAh Lithium Ion",
    cpu: "Processor: Snapdragon 870 Octa-Core",
    screen: "Screen: 2.8K+ Display (11-inch/27.81cm)|1 Billion Colours|144hZ",
    memory: "RAM Size: 8GB",
    hard_disk: "Memory Storage Capacity: 256GB",
    optical_drive: "",
    graphics: "",
    dimension: "Dimensions: 27.8 x 18.9 x 4.9 cm",
    weight: "Net Weight: 1.07 kg",
    brand: "Brand: Xiaomi",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1HLG1rbc5mOsImK2kxKq266_sY4SPLvqD",
    title: "Redmi Pad | MediaTek Helio G99 | 26.95cm (10.61 inch) 2K Resolution & 90Hz Refresh Rate Display | 6GB RAM & 128GB Storage, Expandable up to 1TB | Quad Speaker - Dolby Atmos | Wi-Fi | Graphite Gray",
    price: "799",
    rent: "Rent ₹799/month",
    color: "Color: Graphite Gray",
    desc: "Included Components: Tablet, Adapter, USB C type Cable, SD card ejector, Quick start Guide & Warranty card",
    operating_system: "Operating System: Android",
    features: "Batteries: 8000mAh Lithium Ion",
    cpu: "Processor: Snapdragon 870 Octa-Core",
    screen: "Screen: 10.61 Inches LED 2000 x 1200 pixels",
    memory: "RAM Size: 6GB",
    hard_disk: "Memory Storage Capacity: 128GB",
    optical_drive: "",
    graphics: "",
    dimension: "Dimensions: 25 x 0.7 x 15.8 cm",
    weight: "Net Weight: 465 Grams",
    brand: "Brand: Redmi",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1uSH8p-alEeQDp67auX1oNBAJ-CIwuXkU",
    title: "OnePlus Pad 29.49cm (11.61 inch) LCD Display, 12GB RAM,256GB Storage, MediaTek Dimensity 9000, Android 13.1, 144HZ Refresh Rate, Dolby Vision Atmos, Wi-Fi with Cellular Data Sharing Tablet",
    price: "899",
    rent: "Rent ₹899/month",
    color: "Color: Green",
    desc: "Included Components: OnePlus Pad, SUPERVOOC Power Adapter, Type C cable, Safety Information & Warranty Card, Quick Start Guide",
    operating_system: "Operating System: Android || Oxygen OS 13.1",
    features: "Batteries: 8000mAh Lithium Ion",
    cpu: "Processor: MediaTek Dimensity 9000",
    screen: "Screen: 11.61 inch LCD 2800 x 2000 pixels 144HZ Refresh Rate",
    memory: "RAM Size: 12GB",
    hard_disk: "Memory Storage Capacity: 256GB",
    optical_drive: "",
    graphics: "",
    dimension: "Dimensions: 25.8 x 18.9 x 0.7 cm",
    weight: "Net Weight: 552 Grams",
    brand: "Brand: OnePlus",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=14N980K_kqwZfmHytclL09Aq6zXVd7M-v",
    title: "Lenovo Tab P11 Plus Tablet (11 inch (27.94 cm), 6 GB, 128 GB, Wi-Fi+LTE, Voice Calling), Slate Grey with 2K Display, Quad Speakers with Dolby Atmos, 7700 mAH Battery and TUV Certified Eye Protection",
    price: "899",
    rent: "Rent ₹899/month",
    color: "Color: Slate Grey",
    desc: "Included Components: Lenovo Tab P11 Plus, 10V/2A charging adapter, USB Type-C charging cable, SIM Pin, Quick Start Guide and Safety Warranty",
    operating_system: "Operating System: Android 11",
    features: "Batteries: 7700mAh Lithium Ion",
    cpu: "Processor: Mediatek Helio G90T octa core processor",
    screen: "Screen: 11 inch 2K (2000*1200) display| NTSC 70%| Colour Depth 16.7 million| 400 nits brightness| PPI 213; Display Type - 2K, FHD, IPS; Screen Refresh - 60Hz",
    memory: "RAM Size: 6GB",
    hard_disk: "Memory Storage Capacity: 128GB",
    optical_drive: "",
    graphics: "",
    dimension: "Dimensions: 25.8 x 0.8 x 16.3 cm",
    weight: "Net Weight: 490 Grams",
    brand: "Brand: Lenovo",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1iVT-rV6rQziTdU995M0zQZRi_AC46uze",
    title: "Samsung Galaxy Tab S8 | 27.81cm (11.0-inch) LCD Display | 4nm Processor | 8,000 mAh Battery | Dolby Atmos Quad Speakers | Android 12.0 | 8GB+128GB | 12GB+256GB | Wi-Fi | 5G | S Pen Support | Graphite",
    price: "999",
    rent: "Rent ₹999/month",
    color: "Color: Graphite",
    desc: "Included Components: USB Type C Cable, Ejection Pin, QSG, S-Pen.",
    operating_system: "Operating System: Android 12.0",
    features: "Battery power: 8,000 mAh (typical) Battery | 45W Super-Fast Charger | Share your Tab battery power to your Galaxy Smartphones",
    cpu: "Processor: Lightning fast speeds with the 4nm processor | Snapdragon 8 Gen 1 Mobile Platform | Network/Bearer: Hyperfast 5G | Wi-Fi 6E",
    screen: "Screen: 27.81cm (11.0-inch) display size | LCD screen | 120Hz display | 16M color support | Armor Aluminum casing guards against all sorts of bumps and drops",
    memory: "RAM Size: 12GB",
    hard_disk: "Memory Storage Capacity: 256GB",
    optical_drive: "",
    graphics: "Spacial Features: S Pen Support: Yes (Gesture/Remote Control), Fingerprint Scanner on Power Key, Dolby Atmos quad speakers",
    dimension: "Dimensions: 165.3 x 253.8 x 6.3cm ",
    weight: "Net Weight: 505 Grams",
    brand: "Brand: SAMSUNG",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1DzcEzxiVUOfVkR-x41E1Ye-OQ5tyjsJJ",
    title: "Apple 2022 10.9-inch iPad (Wi-Fi + Cellular, 256GB) - Blue (10th Generation)",
    price: "1199",
    rent: "Rent ₹1199/month",
    color: "Color: Blue",
    desc: "Included Components: iPad, USB-C Woven Charge Cable, 20W USB-C Power Adapter.",
    operating_system: "Operating System: IPadOS",
    features: "Battery power: Up to 10 hours of surfing the web on Wi‑Fi or watching video, Up to 9 hours of surfing the web using cellular data network, Charging via USB-C to computer system or power adapter",
    cpu: "Processor: A14 Bionic chip, 6-core CPU, 4-core graphics, 16-core Neural Engine",
    screen: "Screen: 10.9-inch Liquid Retina display with True Tone",
    memory: "",
    hard_disk: "Memory Storage Capacity: 256GB",
    optical_drive: "",
    graphics: "Spacial Features: Works with Apple Pencil (1st generation) using USB-C to Apple Pencil Adapter - sold separately, Touch ID for secure authentication and Apple Pay",
    dimension: "Dimensions: 9.79 inches X 7.07 inches X  0.28 inch",
    weight: "Net Weight: 1.05 pounds (477 grams) Wi-Fi model; 1.06 pounds (481 grams) Wi-Fi + Cellular model",
    brand: "Brand: Apple",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=18WD58Sic6to_h2xC298MYYUsJysK_oyj",
    title: "Apple 2021 iPad Pro M1 chip (11-inch/27.96 cm, Wi-Fi + Cellular, 1TB) - Space Grey (3rd Generation)",
    price: "1599",
    rent: "Rent ₹1599/month",
    color: "Color: Space Grey",
    desc: "Included Components: iPad Pro USB‑C Charge Cable (1 metre) 20W USB‑C Power Adapter",
    operating_system: "Operating System: IPadOS",
    features: "Battery power: Up to 10 hours of surfing the web on Wi‑Fi or watching video. Up to 9 hours of surfing the web using a mobile data network",
    cpu: "Processor: Apple M1 chip for next-level performance",
    screen: "Screen: Stunning 27.96 cm (11-inch) Liquid Retina display with ProMotion, True Tone, and P3 wide color.",
    memory: "",
    hard_disk: "Memory Storage Capacity: 1TB",
    optical_drive: "",
    graphics: "Spacial Features: Apple Pencil (2nd Generation), Magic Keyboard, Smart Keyboard Folio, Face ID for secure authentication, Four speaker audio and five studio-quality microphones. ",
    dimension: "Dimensions: 247.6 x 178.5 x 5.9mm ",
    weight: "Net Weight: 466 grams (1.03 pounds) Wi‑Fi model. 468 grams (1.03 pounds) Wi‑Fi + Cellular models",
    brand: "Brand: Apple",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1dUKT-CZcwSBHQqs33aXw1eE1rGT05zk9",
    title: "Apple 2021 iPad Pro M1 chip (12.9-inch/32.77 cm, Wi-Fi, 128GB) - Silver (5th Generation)",
    price: "1699",
    rent: "Rent ₹1699/month",
    color: "Color: Silver",
    desc: "Included Components: iPad Pro USB‑C Charge Cable (1 metre) 20W USB‑C Power Adapter",
    operating_system: "Operating System: IPadOS",
    features: "Battery power: Up to 10 hours of surfing the web on Wi‑Fi or watching video. Up to 9 hours of surfing the web using a mobile data network",
    cpu: "Processor: Apple M1 chip for next-level performance",
    screen: "Screen: Brilliant 32.77 cm (12.9-inch) Liquid Retina XDR display with ProMotion, True Tone, and P3 wide color",
    memory: "",
    hard_disk: "Memory Storage Capacity: 128GB",
    optical_drive: "",
    graphics: "Spacial Features: Apple Pencil (2nd Generation), Magic Keyboard, Smart Keyboard Folio, Face ID for secure authentication, Four speaker audio and five studio-quality microphones. ",
    dimension: "Dimensions: 280.6 x 214.9 x 6.4mm ",
    weight: "Net Weight: 682 grams (1.5 pounds) Wi-Fi model, 684 grams (1.51 pounds) Wi‑Fi + Cellular models",
    brand: "Brand: Apple",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
{
    img: "https://drive.google.com/uc?export=download&id=1oqnd71645EPNVsOScGsrsIwm-b0_P6SA",
    title: "Apple 2021 iPad Mini with A15 Bionic chip (Wi-Fi, 64GB) - Starlight (6th Generation)",
    price: "999",
    rent: "Rent ₹999/month",
    color: "Color: Starlight",
    desc: "Included Components: iPad mini, USB-C Charge Cable, 20W USB-C Power Adapter",
    operating_system: "Operating System: IOS 14",
    features: "Battery power: Up to 10 hours of surﬁng the web on Wi‑Fi or watching video. Up to 9 hours of surﬁng the web using cellular data network",
    cpu: "Processor: A15 Bionic chip with 64-bit architecture, 6-core CPU, 5-core graphics, and 16-core Neural Engine",
    screen: "Screen: 8.3 inch (21.08 cm ) Liquid Retina display",
    memory: "",
    hard_disk: "Memory Storage Capacity: 64GB",
    optical_drive: "",
    graphics: "Spacial Features: Apple Pencil (2nd Generation),Smart Keyboard Folio, Bluetooth Keyboards, Touch ID for secure authentication.",
    dimension: "Dimensions: 195.4 x 134.8 x 6.3mm ",
    weight: "Net Weight: 0.65 pound (293 grams) Wi-Fi model, 0.66 pound (297 grams) Wi-Fi + Cellular model",
    brand: "Brand: Apple",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    features: "",
    capacity: "",
    Washing_method: "",
    Type: "",
    material: "",
    size: "",
},
]
let gaming_console_data = [
    {
        img: "https://drive.google.com/uc?export=download&id=1dxSjcl9_5WislR7hDj5CPCgSp1HyTg4h",
        title: "Xbox Series X",
        price: "1399",
        rent: "Rent ₹1399/month",
        color: "Color: BLACk",
        desc: "Included Components: With Xbox Series X, an Xbox Series X console, controller, Ultra High Speed HDMI cable and power cord are included. You can add standalone purchases of Xbox Game Pass and the Seagate Storage Expansion Card for Xbox Series X for the complete experience.",
        operating_system: "",
        features: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: "Dimensions: 37.8 x 29.4 x 21.6 cm",
        weight: "Net Weight: 5.93 Kilograms",
        brand: "Brand: Microsoft",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        features: "",
        capacity: "",
        Washing_method: "",
        Type: "",
        material: "",
        size: "",
    },
    {
        img: "https://drive.google.com/uc?export=download&id=1xh7tlrS2KS8QCnKdqmo6uDXHYwB_y9Y0",
        title: "Xbox Series S",
        price: "999",
        rent: "Rent ₹999/month",
        color: "Color: WHITE",
        desc: "Included Components: With Xbox Series S, an Xbox Series S console, controller, Ultra High Speed HDMI cable and power cord are included. You can add standalone purchases of Xbox Game Pass and the Seagate Storage Expansion Card for Xbox Series S for the complete experience.",
        operating_system: "",
        features: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: "Dimensions: 36 x 29.2 x 12.8 cm",
        weight: "Net Weight: 3.35 Kilograms",
        brand: "Brand: Microsoft",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        features: "",
        capacity: "",
        Washing_method: "",
        Type: "",
        material: "",
        size: "",
    },
    {
        img: "https://drive.google.com/uc?export=download&id=1i_Kfr93Pddb5qnzm8UmrNKe7iB9I-J-h",
        title: "Sony PS5 CoD MWII",
        price: "1499",
        rent: "Rent ₹1499/month",
        color: "",
        desc: "",
        operating_system: "",
        features: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: "Dimensions: 39 x 10.4 x 26 cm",
        weight: "Net Weight: 4.5 Kilograms",
        brand: "Brand: Sony ",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        features: "",
        capacity: "",
        Washing_method: "",
        Type: "",
        material: "",
        size: "",
    },
    {
        img: "https://drive.google.com/uc?export=download&id=14G1XHnDpBpFVrJnkxWZ6gE7Fv0p2Eheq",
        title: "Sony PS5 PlayStation Console",
        price: "1299",
        rent: "Rent ₹1299/month",
        color: "",
        desc: "",
        operating_system: "",
        features: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: "Dimensions:  25.4 x 12.7 x 61 cm",
        weight: "Net Weight: 4.5 Kilograms",
        brand: "Brand: Microsoft",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        features: "",
        capacity: "",
        Washing_method: "",
        Type: "",
        material: "",
        size: "",
    },
]