let bed_data = [{
    img: "https://drive.google.com/uc?export=download&id=1CFXKrcb9MEFFC3LduDuOyW1v2ZhDYOGn",
    title: "DOUBLE MODERN WOODEN BED(6*5) WITH MATTRESS",
    price: "499",
    rent: "Rent ₹499/month",
    desc: "Bed Material Subtype: Particle Board",
    size: "Dimension: W x H x D: 125.4 cm x 79 cm x 203 cm (4 ft 1 in x 2 ft 7 in x 6 ft 7 in)",
    features: "Capacity: 350KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=153O2bJcjBb-wqR2wj48cMdlarc572kzA",
    title: "Solid Wood King Bed WITH MATTRESS",
    price: "699",
    rent: "Rent ₹699/month",
    desc: "Bed Material Subtype: Rosewood (Sheesham)",
    size: "Dimension: W x H x D: 189 cm x 74 cm x 208 cm (6 ft 2 in x 2 ft 5 in x 6 ft 9 in)",
    features: "Capacity: 400KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

}, {
    img: "https://drive.google.com/uc?export=download&id=1AE8XtEh3TxeDlw80Cxde9pl8WxHHnjAS",
    title: "LOW HEIGHT QUEEN SIZE BED WITH MATTRESS",
    price: "799",
    rent: "Rent ₹799/month",
    desc: "Bed Material Subtype: Rosewood (Sheesham)",
    size: "Dimension: W x H x D: 182.88 cm x 76.2 cm x 223.52 cm (6 ft x 2 ft 6 in x 7 ft 3 in)",
    features: "Capacity: 400KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

}, {
    img: "https://drive.google.com/uc?export=download&id=1I1SCMxZ4danZaB5ha86R9Tk1SaCXNaOf",
    title: "SINGLE BED WITH STORAGE(WOODEN) WITH MATTRESS",
    price: "299",
    rent: "Rent ₹299/month",
    desc: "Bed Material Subtype: Plywood",
    size: "Dimension: W x H x D: 96 cm x 81.3 cm x 194 cm (3 ft 1 in x 2 ft 8 in x 6 ft 4 in)",
    features: "Capacity: 200KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

}, {
    img: "https://drive.google.com/uc?export=download&id=1lTjXqxJE4gXYbIvrzK3rQd4PRXPiL20G",
    title: "WOODEN KING SIZE BED WITH MATTRESS",
    price: "499",
    rent: "Rent ₹499/month",
    desc: "Bed Material Subtype: Particle Board",
    size: "Dimension: W x H x D: 187 cm x 37 cm x 223 cm (6 ft 1 in x 1 ft 2 in x 7 ft 3 in)",
    features: "Capacity: 500KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

}, {
    img: "https://drive.google.com/uc?export=download&id=1L8bNKp8GOr4ud4ny1BtKnKKeV6R0AOMO",
    title: "DOUBLE BED WITH MATTRESS",
    price: "489",
    rent: "Rent ₹489/month",
    desc: "Bed Material Subtype: Particle Board",
    size: "Dimension: W x H x D: 188.8 cm x 88 cm x 213.5 cm (6 ft 2 in x 2 ft 10 in x 7 ft)",
    features: "Capacity: 400KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

}, {
    img: "https://drive.google.com/uc?export=download&id=10MRMdPGxgNTMgwApSMn-andSfI9TfWK-",
    title: "SINGLE BED WITH STORAGE (GRAY) WITH MATTRESS",
    price: "299",
    rent: "Rent ₹299/month",
    desc: "Bed Material Subtype: Particle Board",
    size: "Dimension: W x H x D: 95.2 cm x 81.2 cm x 186.6 cm (3 ft 1 in x 2 ft 7 in x 6 ft 1 in)",
    features: "Capacity: 200KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

}, {
    img: "https://drive.google.com/uc?export=download&id=1oNqXAnyNLsr3IIkBfnPNxTVDBd9yDSfa",
    title: "SINGLE BED WITH STORAGE (DARK GRAY) WITH MATTRESS",
    price: "299",
    rent: "Rent ₹299/month",
    desc: "Bed Material Subtype: Particle Board",
    size: "Dimension: W x H x D: 188.8 cm x 90 cm x 213.5 cm (6 ft 2 in x 2 ft 11 in x 7 ft)",
    features: "Capacity: 250KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

}]
let sofa_data = [{
    img: "https://drive.google.com/uc?export=download&id=1g4mRz-2tDOTfMmY58BRNlw6JABKQeNkc",
    title: "Wooden Modern Sofa Chair(GREEN)",
    price: "179",
    rent: "Rent ₹179/month",
    desc: "Upholestry: Velvet   Filling Material: Foam",
    size: "Dimension: W x H x D: 80 cm x 42 cm x 67cm",
    features: "Capacity: 600KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=18jeK158PxaeU-XMSPxocXEH0KzV-UbbW",
    title: "L Shape Fabric 5 Seater Sofa(GRAY)",
    price: "499",
    rent: "Rent ₹499/month",
    desc: "Upholestry: Polycotton   Filling Material: Polyfill   Right Facing",
    size: "Dimension: W x H x D: 246 cm x 70 cm x 188 cm (8 ft x 2 ft 3 in x 6 ft 2 in)",
    features: "Capacity: 600KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=1vH4G8BTwZz5hg3L9f_8dkEnnEQFhJeOs",
    title: "Solid Wood Living Room Chair",
    price: "149",
    rent: "Rent ₹149/month",
    desc: "Material: Solid Wood  Color: Gray",
    size: "Dimension: W x H x D: 680 cm x 760 cm x 710 cm (22 ft 3 in x 24 ft 11 in x 23 ft 3 in)",
    features: "Capacity 100KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=1mRC_Ksd24s1tqN35cvVcZ36tFcln_LHP",
    title: "Light Brown SOFA 3 Seater",
    price: "299",
    rent: "Rent ₹299/month",
    desc: "Upholestry: Velvet   Filling Material: Foam",
    size: "Dimension: W x H x D: 182.626 cm x 71.12 cm x 69.85 cm (5 ft 11 in x 2 ft 4 in x 2 ft 3 in)",
    features: "Capacity: 350KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=1gxy8chh9GIUz1GGRv0aYVHCTxtjpii_g",
    title: "SINGLE SOFA(GRAY)",
    price: "189",
    rent: "Rent ₹189/month",
    desc: "Secondary Material: Solid Wood   Secondary Material Subtype: Pine Wood   Configuration: Straight   Upholstery Material: Fabric   Upholstery Material Subtype: Cotton",
    size: "Dimension: W x H x D: 76 cm x 42 cm x 67cm",
    features: "Capacity: 130KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=1_qI7PytNRCsHODT_d7a3RipWdym6dZBm",
    title: "SINGLE SOFA(BLUE)",
    price: "169",
    rent: "Rent ₹169/month",
    desc: "Upholestry: Cotton   Filling Material: Foam",
    size: "Dimension: W x H x D: 76 cm x 42 cm x 67cm",
    features: "Capacity: 130KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=1v_BSP90udP1eh_EzqDzinMH9GjeHHigs",
    title: "SINGLE SOFA(GREEN)",
    price: "159",
    rent: "Rent ₹159/month",
    desc: "Upholestry: Cotton   Filling Material: Foam",
    size: "Dimension: W x H x D: 100 cm x 42 cm x 67cm",
    features: "Capacity: 120KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=1NnqUrGFXqbBgikcbApAnJH6OoM9w6rT6",
    title: "SINGLE SOFA(GREY)",
    price: "119",
    rent: "Rent ₹119/month",
    desc: "Upholestry: Velvet   Filling Material: Foam",
    size: "Dimension: W x H x D: 70 cm x 42 cm x 67cm",
    features: "Capacity: 100KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=13HhYtDOgvR--v07qvIV8kcgbwEWqI5cV",
    title: "SOFA CUM BED(GRAY)",
    price: "699",
    rent: "Rent ₹699/month",
    desc: "Mattress Included: Yes    Seat Capacity: 3 Seater",
    size: "Dimension: W x H x D: 195 cm x 84 cm x 65 cm (6 ft 4 in x 2 ft 9 in x 2 ft 1 in)",
    features: "Capacity: 350KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=128rjdktqj1Ygdq489ogF1L8F_79wIs0E",
    title: "Sofa With Pillow(4 Pillow)",
    price: "389",
    rent: "Rent ₹389/month",
    desc: "Material: Solid Wood  Upholestry: Velvet   Filling Material: Foam",
    size: "Dimension: W x H x D: 680 cm x 760 cm x 710 cm (22 ft 3 in x 24 ft 11 in x 23 ft 3 in)",
    features: "Capacity 300KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=1QPYdU3WjIRDtMPUvEKgwpuAYmKhdB2S8",
    title: "SOLID WOODEN SOFA CUM BED(With Pillow)",
    price: "489",
    rent: "Rent ₹489/month",
    desc: "Mattress Included: Yes    Seat Capacity: 3 Seater",
    size: "Dimension: W x H x D: 195 cm x 84 cm x 65 cm (6 ft 4 in x 2 ft 9 in x 2 ft 1 in)",
    features: "Capacity: 350KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}, {
    img: "https://drive.google.com/uc?export=download&id=1Zc0MDNzP9yUgBjIg0NVwH0gkXFkBHXPS",
    title: "SOLID WOODEN SOFA CUM BED(BROWN)",
    price: "399",
    rent: "Rent ₹399/month",
    desc: "Mattress Included: Yes    Seat Capacity: 2 Seater",
    size: "Dimension: W x H x D: 195 cm x 84 cm x 65 cm (6 ft 4 in x 2 ft 9 in x 2 ft 1 in)",
    features: "Capacity: 250KG",
    brand: "Brand: RENT KARO",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
}]
let table_data = [{
    img: "https://drive.google.com/uc?export=download&id=1hBXlriTOpxPDFyldqzD65Wzr250YLBAm",
    title: "Wood 4 Seater Dining Table With 4 Chairs For Dining Room",
    price: "399",
    rent: "Rent ₹399/month",
    desc: "Table Top Material: Solid Wood    Chair Frame: Solid Wood   Seating Capacity: 4 Seater",
    size: "Table (W x H x D): 132.08 cm x 76.2 cm x 81.28 cm (4 ft 4 in x 2 ft 6 in x 2 ft 7 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

},
{
    img: "https://drive.google.com/uc?export=download&id=1qG5naovllsM4XtDQZYYf7kWYh1bAi0g7",
    title: "Wood 8 Seater Dining Table With 8 Chairs For Dining Room",
    price: "499",
    rent: "Rent ₹499/month",
    desc: "Table Top Material: Glass   Chair Frame: Solid Wood   Seating Capacity: 8 Seater",
    size: "Table (W x H x D): 203.2 cm x 76.2 cm x 88.9 cm (6 ft 8 in x 2 ft 6 in x 2 ft 10 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

},
{
    img: "https://drive.google.com/uc?export=download&id=1InLHvC22avJoXFqlmhiV4z39RccwrSd0",
    title: "Coffee Tables Round table Wood",
    price: "89",
    rent: "Rent ₹89/month",
    desc: "Table Material: Solid Wood",
    size: "Dimension: W x H x D: 30.48 cm x 33.02 cm x 30.48 cm (1 ft x 1 ft 1 in x 1 ft)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

},
{
    img: "https://drive.google.com/uc?export=download&id=1L-b2SLjHf-H6H56OKkHG_ekId9ThKXdv",
    title: "Computer Desk",
    price: "100",
    rent: "Rent ₹100/month",
    desc: "Computer Desk   Modular Set-up for Study & Home Office with Storage Space   With CPU Compartment   Built-in Keyboard Tray",
    size: "Dimension: W x H x D: 121.9 cm x 73.6 cm x 40.6 cm (3 ft 11 in x 2 ft 4 in x 1 ft 3 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

},
{
    img: "https://drive.google.com/uc?export=download&id=1AURU4BKbc4Zq8o1xDgmZFhXoRz3MRxkX",
    title: "Round White Side Table",
    price: "99",
    rent: "Rent ₹99/month",
    desc: "Table Material: Solid Wood",
    size: "Dimension: W x H x D: 30.48 cm x 70 cm x 30.48 cm (1 ft x 1 ft 1 in x 1 ft)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

},
{
    img: "https://drive.google.com/uc?export=download&id=1sHYaA6Ds4vXs45sua1WMv34mFD-bA4xP",
    title: "Computer Desk",
    price: "100",
    rent: "Rent ₹100/month",
    desc: "Computer Desk   Modular Set-up for Study & Home Office with Storage Space   With CPU Compartment   Built-in Keyboard Tray",
    size: "Dimension: W x H x D: 121.9 cm x 73.6 cm x 40.6 cm (3 ft 11 in x 2 ft 4 in x 1 ft 3 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

}, {
    img: "https://drive.google.com/uc?export=download&id=1Oopljj3urwYkzaEw3QRjdcxo2XvxbFY-",
    title: "Wood Tea Table  (Finish Color - Natural Wallnut)",
    price: "180",
    rent: "Rent ₹180/month",
    desc: "Table Material: Solid Wood    Table Top: Glass",
    size: "Dimension: W x H x D: 87.6 cm x 45.7 cm x 53.3 cm (2 ft 10 in x 1 ft 5 in x 1 ft 8 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

}, {
    img: "https://drive.google.com/uc?export=download&id=1HoSv5LYtgjxjKK9fk8DyexkVBAMObhgK",
    title: "TEA TABLE(WOOD & GLASS)",
    price: "130",
    rent: "Rent ₹130/month",
    desc: "Table Material: Solid Wood    Table Top: Glass",
    size: "Dimension: W x H x D: 87.6 cm x 45.7 cm x 53.3 cm (2 ft 10 in x 1 ft 5 in x 1 ft 8 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

}]

let almirah_data = [
    {
        img: "https://drive.google.com/uc?export=download&id=1g8PyUbxDV7bYDwR8DA1IuWJB1YhUnYoZ",
        title: "Wood Cupboard(Ice Brown)",
        price: "249",
        rent: "Rent ₹249/month",
        desc: "Contemporary & Modern Style   Suitable For: Storage",
        size: "Dimension: W x H x D: 60 cm x 147.4 cm x 38.1 cm (1 ft 11 in x 4 ft 10 in x 1 ft 3 in)",
        brand: "Brand: RENT KARO",
        features: "",
        weight: "",
        capacity: "",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        Washing_method: "",
        Type: "",
        material: "",
        color: "",
        operating_system: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: ""
    },
    {
        img: "https://drive.google.com/uc?export=download&id=1EpjMsSmibQsBGIGNcIaOMM7ba4oyYR-s",
        title: "Wooden WARDDROBE(BEIGE)",
        price: "299",
        rent: "Rent ₹299/month",
        desc: "Primary Material: Engineered Wood",
        size: "Dimension: W x H x D: 100 cm x 147.4 cm x 38.1 cm (1 ft 11 in x 4 ft 10 in x 1 ft 3 in)",
        brand: "Brand: RENT KARO",
        features: "",
        weight: "",
        capacity: "",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        Washing_method: "",
        Type: "",
        material: "",
        color: "",
        operating_system: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: ""
    },
    {
        img: "https://drive.google.com/uc?export=download&id=1Xu-GqW8Z23No63V1d22SIb5C9gjHUKF0",
        title: "Engineered Wood 4 Door Wardrobe(With MIRROR)",
        price: "130",
        rent: "Rent ₹130/month",
        desc: "Primary Material: Engineered Wood",
        size: "Dimension: Width x Height: 150 cm x 201 cm (4 ft 5 in x 6 ft 7 in)",
        brand: "Brand: RENT KARO",
        features: "",
        weight: "",
        capacity: "",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        Washing_method: "",
        Type: "",
        material: "",
        color: "",
        operating_system: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: ""
    },
    {
        img: "https://drive.google.com/uc?export=download&id=1f70JvQsEirWj3NdMrhr_iOfIV38lOSNt",
        title: "STEEL WARDROBE WITH MIRROR(SKY BLUE)",
        price: "199",
        rent: "Rent ₹199/month",
        desc: "Table Material: STEEL    ON DOOR: Glass",
        size: "Dimension: Width x Height: 75 cm x 120 cm (2 ft 4 in x 3 ft 9 in)",
        brand: "Brand: RENT KARO",
        features: "",
        weight: "",
        capacity: "",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        Washing_method: "",
        Type: "",
        material: "",
        color: "",
        operating_system: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: ""
    },
    {
        img: "https://drive.google.com/uc?export=download&id=13aGgqCJAzYKUhaZGPs8jsaOdyOfXHdDt",
        title: "STEEL WARDROBE WITH MIRROR(PURPLE)",
        price: "199",
        rent: "Rent ₹199/month",
        desc: "Table Material: STEEL   ON DOOR: Glass",
        size: "Dimension: Width x Height: 90 cm x 120 cm (2 ft 9 in x 6 ft 7 in)",
        brand: "Brand: RENT KARO",
        features: "",
        weight: "",
        capacity: "",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        Washing_method: "",
        Type: "",
        material: "",
        color: "",
        operating_system: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: ""
    },
    {
        img: "https://drive.google.com/uc?export=download&id=1bEv10H087ar5WNWLEgZ07joMgsi2sbOR",
        title: "STEEL 2 DOOR ALMIRAH(GRAY)",
        price: "189",
        rent: "Rent ₹189/month",
        desc: "Table Material: STEEL",
        size: "Dimension: Width x Height: 100 cm x 120 cm (3 ft 2 in x 6 ft 7 in)",
        brand: "Brand: RENT KARO",
        features: "",
        weight: "",
        capacity: "",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        Washing_method: "",
        Type: "",
        material: "",
        color: "",
        operating_system: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: ""
    },
    {
        img: "https://drive.google.com/uc?export=download&id=1NXbHMOG8-jUVvsE98DzfXK6oCxbJharU",
        title: "STEEL 2 DOOR ALMIRAH(BROWN)",
        price: "169",
        rent: "Rent ₹169/month",
        desc: "Table Material: STEEL",
        size: "Dimension: Width x Height: 60 cm x 120 cm (1 ft 9 in x 6 ft 7 in)",
        brand: "Brand: RENT KARO",
        features: "",
        weight: "",
        capacity: "",
        Indoor_unit_size: "",
        Indoor_unit_weight: "",
        Outdoor_unit_size: "",
        Outdoor_unit_weight: "",
        Washing_method: "",
        Type: "",
        material: "",
        color: "",
        operating_system: "",
        cpu: "",
        screen: "",
        memory: "",
        hard_disk: "",
        optical_drive: "",
        graphics: "",
        dimension: ""
    }

]

let chair_data = [{
    img: "https://drive.google.com/uc?export=download&id=1hoW72seU9mBtV87FVGm896TI2rMAjB4D",
    title: "Mid Back Ergonomic|Home, Office, WFH|Moulded Foam|Extra Comfort Fabric Office Adjustable Arm Chair(Multicolour)",
    price: "189",
    rent: "Rent ₹189/month",
    desc: "Adjustable Seat Height, Armrest, Locking Mechanism, Seat Lock, Wheels   Frame Material: Metal    Upholstery Type: Cushion",
    size: "Dimension: W x H: 59.5 cm x 92.5 cm (1 ft 11 in x 3 ft)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1uulRLNobrgJqQU4_fNSIVBwbaLRZEyX0",
    title: "OFFICE CHAIR Fabric Office Executive Chair(Black)",
    price: "129",
    rent: "Rent ₹129/month",
    desc: "Frame Material: Metal    Upholstery Type: Cushion",
    size: "Dimension: Width x Height: 60 cm x 95 cm (1 ft 9 in x 6 ft 7 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""

},
{
    img: "https://drive.google.com/uc?export=download&id=1iQpjaYndgEao3ObQVIHSpdyF_XBzzVkD",
    title: "HIGH Back Leather Office with adjustable handle for home and office Leatherette Office Executive Chair(Brown)",
    price: "299",
    rent: "Rent ₹299/month",
    desc: "Adjustable Seat Height, Armrest, Locking Mechanism, Seat Lock, Wheels   Frame Material: Metal    Upholstery Type: Cushion",
    size: "Dimension: W x H: 56 cm x 124 cm (1 ft 10 in x 4 ft)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1yJYkEGRC93s74PnIsFWbPq7g22xUi-70",
    title: "High Back Comfortable Mesh Office Arm Chair(Black & Silver)",
    price: "239",
    rent: "Rent ₹239/month",
    desc: "Adjustable Seat Height, Armrest, Head Support, Locking Mechanism, Recline, Seat Lock, Swivel, Wheels   Frame Material: Engineered Wood   Upholstery Type: Mesh",
    size: "Dimension: W x H: 69 cm x 138 cm (2 ft 3 in x 4 ft 6 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1D-Edgg7ttr9KzSla0qL6ppuiqlcF0tSf",
    title: "Chair",
    price: "169",
    rent: "Rent ₹169/month",
    desc: "Table Material: STEEL",
    size: "Dimension: Width x Height: 60 cm x 120 cm (1 ft 9 in x 6 ft 7 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1PhVYHTYIl113oVO9uBDtIP9bx5ULlPN1",
    title: "Chair",
    price: "169",
    rent: "Rent ₹169/month",
    desc: "Table Material: STEEL",
    size: "Dimension: Width x Height: 60 cm x 120 cm (1 ft 9 in x 6 ft 7 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1-zSS1QETEbfdHHy6AVZph8kZM7BWvfOJ",
    title: "HIGH Back Leatherette Office with Steel Base and Warranty Leatherette Office Executive Chair(Beige)",
    price: "299",
    rent: "Rent ₹299/month",
    desc: "Adjustable Seat Height, Armrest, Head Support, Locking Mechanism, Seat Lock, Wheels   Frame Material: Metal    Upholstery Type: Cushion",
    size: "Dimension: W x H: 53 cm x 121 cm (1 ft 8 in x 3 ft 11 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1rKqbwcLCvAUu8_NvA0tHgp1Ouch0oWxg",
    title: "High Back Revolving Office Chair Leatherette Office Executive Chair(Black)",
    price: "269",
    rent: "Rent ₹269/month",
    desc: "Adjustable Seat Height, Wheels, Armrest, Wheels      Upholstery Type: Cushion",
    size: "Dimension: W x H: 53.34 cm x 121.92 cm (1 ft 9 in x 4 ft)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1KJ12TY4g8fZe4E8-AC4mn9LeoTMENWWZ",
    title: "Chair",
    price: "169",
    rent: "Rent ₹169/month",
    desc: "Table Material: STEEL",
    size: "Dimension: Width x Height: 60 cm x 120 cm (1 ft 9 in x 6 ft 7 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=188r4onIH5dbh0AEZOzPfgyJuRbxEfqPt",
    title: "Chair",
    price: "169",
    rent: "Rent ₹169/month",
    desc: "Table Material: STEEL",
    size: "Dimension: Width x Height: 60 cm x 120 cm (1 ft 9 in x 6 ft 7 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1NAI4yuT2PMRVIP-NZPnAcg3AiijhNdAc",
    title: "Chair",
    price: "169",
    rent: "Rent ₹169/month",
    desc: "Table Material: STEEL",
    size: "Dimension: Width x Height: 60 cm x 120 cm (1 ft 9 in x 6 ft 7 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1oiKmoiiJ8Jdjf_Ndeobpix-pE5zYShNA",
    title: "Chair",
    price: "169",
    rent: "Rent ₹169/month",
    desc: "Table Material: STEEL",
    size: "Dimension: Width x Height: 60 cm x 120 cm (1 ft 9 in x 6 ft 7 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1doiBpU6D3CXwYptvV9QL1cbNmprzpY8X",
    title: "Chair",
    price: "169",
    rent: "Rent ₹169/month",
    desc: "Table Material: STEEL",
    size: "Dimension: Width x Height: 60 cm x 120 cm (1 ft 9 in x 6 ft 7 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},
{
    img: "https://drive.google.com/uc?export=download&id=1NL0m6KKlWtg9n6d-yZrkyY0b5JJESiN5",
    title: "Chair",
    price: "169",
    rent: "Rent ₹169/month",
    desc: "Table Material: STEEL",
    size: "Dimension: Width x Height: 60 cm x 120 cm (1 ft 9 in x 6 ft 7 in)",
    brand: "Brand: RENT KARO",
    features: "",
    weight: "",
    capacity: "",
    Indoor_unit_size: "",
    Indoor_unit_weight: "",
    Outdoor_unit_size: "",
    Outdoor_unit_weight: "",
    Washing_method: "",
    Type: "",
    material: "",
    color: "",
    operating_system: "",
    cpu: "",
    screen: "",
    memory: "",
    hard_disk: "",
    optical_drive: "",
    graphics: "",
    dimension: ""
},]

